name: PostgreSQL to Snowflake Sync

on:
  schedule:
    - cron: '0 */4 * * *'  # Run every 4 hours
  workflow_dispatch:  # Allow manual triggering

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build TypeScript
        run: npm run build
      
      - name: Run sync script
        env:
          # PostgreSQL Configuration
          PG_HOST: ${{ secrets.PG_HOST }}
          PG_PORT: ${{ secrets.PG_PORT }}
          PG_DATABASE: ${{ secrets.PG_DATABASE }}
          PG_USER: ${{ secrets.PG_USER }}
          PG_PASSWORD: ${{ secrets.PG_PASSWORD }}
          PG_REPLICATION_SLOT: ${{ secrets.PG_REPLICATION_SLOT }}
          PG_PUBLICATION_NAME: ${{ secrets.PG_PUBLICATION_NAME }}
          
          # Snowflake Configuration
          SF_ACCOUNT: ${{ secrets.SF_ACCOUNT }}
          SF_USERNAME: ${{ secrets.SF_USERNAME }}
          SF_PASSWORD: ${{ secrets.SF_PASSWORD }}
          SF_DATABASE: ${{ secrets.SF_DATABASE }}
          SF_SCHEMA: ${{ secrets.SF_SCHEMA }}
          SF_WAREHOUSE: ${{ secrets.SF_WAREHOUSE }}
          SF_ROLE: ${{ secrets.SF_ROLE }}
          
          # Sync Configuration
          EXCLUDED_TABLES: ${{ secrets.EXCLUDED_TABLES }}
          STATE_FILE_PATH: './sync-state.json'
        run: node dist/pg-to-snowflake-sync.js
      
      - name: Archive sync state
        uses: actions/upload-artifact@v3
        with:
          name: sync-state
          path: sync-state.json
          retention-days: 7 